name: arbeit
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.11.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  step_progress_indicator: ^1.0.2
  flutter_svg: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

fonts:
  - family: Axiforma
    fonts:
      - asset: assets/fonts/Axiforma-Black.ttf
        weight: 900
      - asset: assets/fonts/Axiforma-Bold.ttf
        weight: 700
      - asset: assets/fonts/Axiforma-ExtraBold.ttf
        weight: 800
      - asset: assets/fonts/Axiforma-Italic.ttf
        weight: 200
      - asset: assets/fonts/Axiforma-Light.ttf
        weight: 300
      - asset: assets/fonts/Axiforma-Medium.ttf
        weight: 500
      - asset: assets/fonts/Axiforma-Regular.ttf
        weight: 400
      - asset: assets/fonts/Axiforma-SemiBold.ttf
        weight: 600
      - asset: assets/fonts/Axiforma-Thin.ttf
        weight: 100

flutter:
  uses-material-design: true
  assets:
    - assets/images/
